### ISSUE TITLE
[layout] collapsible sidebar

### ISSUE THREAD

**Issue by resir014** [kata-ai/wicara#59]
In mobile view, the sidebar should collapse to the left, and be toggleable by menu. This would be really helpful for implementing responsive design.

**Comment by teevik** [comment]
Hey, i could work on this

So it would be toggled by a hamburger button right?

**Comment by resir014** [comment]
@teevik Yes. Would you like some design references to help you with?

**Comment by teevik** [comment]
Sure!

**Comment by teevik** [comment]
Sure!

**Comment by resir014** [comment]
Alright.

For now we can follow Bitbucket's style.

Closed mobile drawer, with a toggle icon.

![image](https://user-images.githubusercontent.com/5663877/48117899-30b96780-e29d-11e8-9d85-628584acf800.png)

Slides out from the left side with an overlay. Click on overlay to close.

![image](https://user-images.githubusercontent.com/5663877/48117933-40d14700-e29d-11e8-8c15-3742f4b8e84a.png)

Feel free to use the Layout part of the Storybook to test things out, or [this starter kit](https://github.com/kata-ai/wicara-starter) for a semi-real implementation.

**Comment by teevik** [comment]
If there's no topbar, should the sidebar always be shown? Since there would be no way to toggle it on mobile

**Comment by resir014** [comment]
Hm. That's an interesting thing I never thought about.

We do have an alternate design which involves popout buttons like this. We can use this one instead:

![image](https://user-images.githubusercontent.com/5663877/48237879-52306580-e3fb-11e8-997b-268bee065ccf.png)

**Comment by teevik** [comment]
Hey, I'm sorry but i don't think i can do this
I kinda got half of it done, but i just feel like I'm making a big mess, and don't have enough time

So if anyone else wants to work on this, go ahead!

**Comment by resir014** [comment]
Due to changes in the roadmap, we're no longer going forward with this issue.
